### ISSUE TITLE
Windowsでのrtcwdの実行

### ISSUE THREAD

**Issue by kkunita-work** [OpenRTM/rtshell#10]
カレントディレクトリが書き込み権限のないディレクトリだった場合(例えばC:\)、エラーが発生する。C:\でrtcwdで発生。
修正は、rtcwd.batが書き込んでCallするファイルをカレントディレクトリでなくTEMPディレクトリにすれば良さそう。

**Comment by n-kawauchi** [comment]
rtcwdの実行でエラーになるのは、rtcwd.exeが存在しないからではないでしょうか。
これってsetup.pyのsetuptools.setup関数での指定が抜けているのが原因のような気がします。

**Comment by kkunita-work** [comment]
作られたrtcwd.batファイルを編集してcopyされるbatファイルをTEMPディレクトリの下にコピーするとエラーが発生しなくなります。rtshell_post_installでこのbatファイルがコピーされるようになっているようです。従ってWindowsでもrtshell_post_installが必要です。

**Comment by n-kawauchi** [comment]
Pythonが Program Files下にインストールされている場合は、確かに Permission denied になります。
この場合、コマンドを管理者で実行すれば問題なくインストールされます。
```
>rtshell_post_install -n
Running post-install actions for Windows
Copied c:\program files\python36\lib\site-packages\rtshell\data\rtcwd.bat to c:\program files\python36\Scripts\rtcwd.bat
```

#13 の手順でインストールした rtcwd でワーキングディレクトリを変更する動作も確認できましたので、このIssueは閉じます。
