### ISSUE TITLE
RTSystemEditorでセーブしたxmlファイルがrtshellのRTSProfileファイルを扱うコマンドでうまく扱えない

### ISSUE THREAD

**Issue by kkunita-work** [OpenRTM/rtshell#11]
WindowsのPython3.7を使っている環境でおこりました。(現状RTProfile関係のrtshellのコマンドはwindowsでPython3をいれないと動かないため、他の環境ではチェックできません。)

1. C++版のConsoleInとConsoleOutのサンプルを起動
2. RTSystemEditorで接続等の設定をしてActivateして動作確認
3. コマンドプロンプトからrtcryo localhost >test1.xml
4. RTSystemEditor のSystem Diagramで右クリックでSave Asをして、test2.xmlでファイルを保管
5. RTSystemEditorで、SystemをDeactivate
6. コマンドプロンプトからrtstart test1.xml
 ConsoleInとConsoleOutのサンプルが動くことを確認
8. コマンドプロンプトからrtstop teet1.xml
 RTSEの画面でコンポーネントが青になりDeactivateされるのを確認
9. コマンドプロンプトでrtstart test2.xmlとする
本来は６を実行した時と同じになるはずだが、
rtstart: rts_profile.abstract
と表示され、RTSEの画面は変わらず

現状の1.2.1リリースではRTSEとrtshellでのRTSProfileデータに互換性がないようです。どちらかを直宇必要があります。
テストしたtest1.xmlとtest2.xmlを添付しました。

[RTSProfileTest.zip](https://github.com/OpenRTM/rtshell/files/4347381/RTSProfileTest.zip)

**Comment by n-kawauchi** [comment]
OpenRTM-aist 1.2.2, rtshell-aist 4.2.7, rtctree-aist 4.2.2, rtsprofile-aist 4.1.4
上記をインストールしているWindows10、Ubuntu18.04 環境で確認したところ問題なかったため、このIssueはCloseします。
